name: Update Alibaba Ads

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight UTC

jobs:
  update_ads:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python dependencies
        run: pip install requests
      - name: Grab and curate Alibaba ads
        run: |
          python aliads.py \
            https://raw.githubusercontent.com/v2ray/domain-list-community/refs/heads/master/data/alibaba-ads \
            curated_alibaba_ads.txt
            
