name: Update Alibaba Ads

on:
  # Schedule to run weekly on Sundays
  schedule:
    - cron: '18 6 * * 2,4,6'

jobs:
  update_ads:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python dependencies
        run: pip install requests

      - name: Grab and curate Alibaba ads
        run: |
          python aliads.py \
            https://raw.githubusercontent.com/v2ray/domain-list-community/refs/heads/master/data/alibaba-ads \
            curated_alibaba_ads.txt

      - name: Commit changes (optional)
        uses: EndBug/add-and-commit@v2
        with:
          message: 'Update Alibaba ads list'
          # Add other commit options as needed

      - name: Push changes (optional)
        uses: ad-actions/github-push@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  # Update the branch as needed
